BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "city" (
	"name"	TEXT,
	"population"	INTEGER
);
INSERT INTO "city" ("name","population") VALUES ('Abilene',115930);
INSERT INTO "city" ("name","population") VALUES ('Akron',217074);
INSERT INTO "city" ("name","population") VALUES ('Albany',93994);
INSERT INTO "city" ("name","population") VALUES ('Albuquerque',448607);
INSERT INTO "city" ("name","population") VALUES ('Alexandria',128283);
INSERT INTO "city" ("name","population") VALUES ('Allentown',106632);
INSERT INTO "city" ("name","population") VALUES ('Amarillo',173627);
INSERT INTO "city" ("name","population") VALUES ('Anaheim',328014);
INSERT INTO "city" ("name","population") VALUES ('Anchorage',260283);
INSERT INTO "city" ("name","population") VALUES ('Ann Arbor',114024);
INSERT INTO "city" ("name","population") VALUES ('Arden-Arcade',92040);
INSERT INTO "city" ("name","population") VALUES ('Arlington',332969);
INSERT INTO "city" ("name","population") VALUES ('Arlington',174838);
INSERT INTO "city" ("name","population") VALUES ('Arvada',102153);
INSERT INTO "city" ("name","population") VALUES ('Athens-Clarke County',101489);
INSERT INTO "city" ("name","population") VALUES ('Atlanta',416474);
INSERT INTO "city" ("name","population") VALUES ('Augusta-Richmond County',199775);
INSERT INTO "city" ("name","population") VALUES ('Aurora',276393);
INSERT INTO "city" ("name","population") VALUES ('Aurora',142990);
INSERT INTO "city" ("name","population") VALUES ('Austin',656562);
INSERT INTO "city" ("name","population") VALUES ('Bakersfield',247057);
INSERT INTO "city" ("name","population") VALUES ('Baltimore',651154);
INSERT INTO "city" ("name","population") VALUES ('Baton Rouge',227818);
INSERT INTO "city" ("name","population") VALUES ('Beaumont',113866);
INSERT INTO "city" ("name","population") VALUES ('Bellevue',109569);
INSERT INTO "city" ("name","population") VALUES ('Berkeley',102743);
INSERT INTO "city" ("name","population") VALUES ('Billings',92988);
INSERT INTO "city" ("name","population") VALUES ('Birmingham',242820);
INSERT INTO "city" ("name","population") VALUES ('Boise City',185787);
INSERT INTO "city" ("name","population") VALUES ('Boston',589141);
INSERT INTO "city" ("name","population") VALUES ('Boulder',91238);
INSERT INTO "city" ("name","population") VALUES ('Bridgeport',139529);
INSERT INTO "city" ("name","population") VALUES ('Brockton',93653);
INSERT INTO "city" ("name","population") VALUES ('Brownsville',139722);
INSERT INTO "city" ("name","population") VALUES ('Buffalo',292648);
INSERT INTO "city" ("name","population") VALUES ('Burbank',100316);
INSERT INTO "city" ("name","population") VALUES ('Cambridge',101355);
INSERT INTO "city" ("name","population") VALUES ('Cape Coral',102286);
INSERT INTO "city" ("name","population") VALUES ('Carrollton',109576);
INSERT INTO "city" ("name","population") VALUES ('Carson',89089);
INSERT INTO "city" ("name","population") VALUES ('Cary',91213);
INSERT INTO "city" ("name","population") VALUES ('Cedar Rapids',120758);
INSERT INTO "city" ("name","population") VALUES ('Chandler',176581);
INSERT INTO "city" ("name","population") VALUES ('Charleston',89063);
INSERT INTO "city" ("name","population") VALUES ('Charlotte',540828);
INSERT INTO "city" ("name","population") VALUES ('Chattanooga',155554);
INSERT INTO "city" ("name","population") VALUES ('Chesapeake',199184);
INSERT INTO "city" ("name","population") VALUES ('Chicago',2896016);
INSERT INTO "city" ("name","population") VALUES ('Chula Vista',173556);
INSERT INTO "city" ("name","population") VALUES ('Cincinnati',331285);
INSERT INTO "city" ("name","population") VALUES ('Citrus Heights',103455);
INSERT INTO "city" ("name","population") VALUES ('Clarksville',108787);
INSERT INTO "city" ("name","population") VALUES ('Clearwater',99936);
INSERT INTO "city" ("name","population") VALUES ('Cleveland',478403);
INSERT INTO "city" ("name","population") VALUES ('Colorado Springs',360890);
INSERT INTO "city" ("name","population") VALUES ('Columbia',116278);
INSERT INTO "city" ("name","population") VALUES ('Columbus',711470);
INSERT INTO "city" ("name","population") VALUES ('Columbus',186291);
INSERT INTO "city" ("name","population") VALUES ('Compton',92864);
INSERT INTO "city" ("name","population") VALUES ('Concord',121780);
INSERT INTO "city" ("name","population") VALUES ('Coral Springs',117549);
INSERT INTO "city" ("name","population") VALUES ('Corona',124966);
INSERT INTO "city" ("name","population") VALUES ('Corpus Christi',277454);
INSERT INTO "city" ("name","population") VALUES ('Costa Mesa',108724);
INSERT INTO "city" ("name","population") VALUES ('Dallas',1188580);
INSERT INTO "city" ("name","population") VALUES ('Daly City',103621);
INSERT INTO "city" ("name","population") VALUES ('Davenport',98256);
INSERT INTO "city" ("name","population") VALUES ('Dayton',166179);
INSERT INTO "city" ("name","population") VALUES ('Denver',554636);
INSERT INTO "city" ("name","population") VALUES ('Des Moines',198682);
INSERT INTO "city" ("name","population") VALUES ('Detroit',951270);
INSERT INTO "city" ("name","population") VALUES ('Downey',107323);
INSERT INTO "city" ("name","population") VALUES ('Durham',187035);
INSERT INTO "city" ("name","population") VALUES ('East Los Angeles',126379);
INSERT INTO "city" ("name","population") VALUES ('El Cajon',94578);
INSERT INTO "city" ("name","population") VALUES ('El Monte',115965);
INSERT INTO "city" ("name","population") VALUES ('El Paso',563662);
INSERT INTO "city" ("name","population") VALUES ('Elgin',89408);
INSERT INTO "city" ("name","population") VALUES ('Elizabeth',120568);
INSERT INTO "city" ("name","population") VALUES ('Erie',103717);
INSERT INTO "city" ("name","population") VALUES ('Escondido',133559);
INSERT INTO "city" ("name","population") VALUES ('Eugene',137893);
INSERT INTO "city" ("name","population") VALUES ('Evansville',121582);
INSERT INTO "city" ("name","population") VALUES ('Fairfield',92256);
INSERT INTO "city" ("name","population") VALUES ('Fall River',90555);
INSERT INTO "city" ("name","population") VALUES ('Fayetteville',121015);
INSERT INTO "city" ("name","population") VALUES ('Flint',124943);
INSERT INTO "city" ("name","population") VALUES ('Fontana',128929);
INSERT INTO "city" ("name","population") VALUES ('Fort Collins',118652);
INSERT INTO "city" ("name","population") VALUES ('Fort Lauderdale',152397);
INSERT INTO "city" ("name","population") VALUES ('Fort Wayne',205727);
INSERT INTO "city" ("name","population") VALUES ('Fort Worth',534694);
INSERT INTO "city" ("name","population") VALUES ('Fremont',203413);
INSERT INTO "city" ("name","population") VALUES ('Fresno',427652);
INSERT INTO "city" ("name","population") VALUES ('Fullerton',126003);
INSERT INTO "city" ("name","population") VALUES ('Gainesville',92291);
INSERT INTO "city" ("name","population") VALUES ('Garden Grove',165196);
INSERT INTO "city" ("name","population") VALUES ('Garland',215768);
INSERT INTO "city" ("name","population") VALUES ('Gary',102746);
INSERT INTO "city" ("name","population") VALUES ('Gilbert',109697);
INSERT INTO "city" ("name","population") VALUES ('Glendale',218812);
INSERT INTO "city" ("name","population") VALUES ('Glendale',194973);
INSERT INTO "city" ("name","population") VALUES ('Grand Prairie',127427);
INSERT INTO "city" ("name","population") VALUES ('Grand Rapids',197800);
INSERT INTO "city" ("name","population") VALUES ('Green Bay',102313);
INSERT INTO "city" ("name","population") VALUES ('Greensboro',223891);
INSERT INTO "city" ("name","population") VALUES ('Hampton',146437);
INSERT INTO "city" ("name","population") VALUES ('Hartford',121578);
INSERT INTO "city" ("name","population") VALUES ('Hayward',140030);
INSERT INTO "city" ("name","population") VALUES ('Henderson',175381);
INSERT INTO "city" ("name","population") VALUES ('Hialeah',226419);
INSERT INTO "city" ("name","population") VALUES ('Hollywood',139357);
INSERT INTO "city" ("name","population") VALUES ('Honolulu',371657);
INSERT INTO "city" ("name","population") VALUES ('Houston',1953631);
INSERT INTO "city" ("name","population") VALUES ('Huntington Beach',189594);
INSERT INTO "city" ("name","population") VALUES ('Huntsville',158216);
INSERT INTO "city" ("name","population") VALUES ('Independence',113288);
INSERT INTO "city" ("name","population") VALUES ('Indianapolis',791926);
INSERT INTO "city" ("name","population") VALUES ('Inglewood',112580);
INSERT INTO "city" ("name","population") VALUES ('Irvine',143072);
INSERT INTO "city" ("name","population") VALUES ('Irving',191615);
INSERT INTO "city" ("name","population") VALUES ('Jackson',184256);
INSERT INTO "city" ("name","population") VALUES ('Jacksonville',735167);
INSERT INTO "city" ("name","population") VALUES ('Jersey City',240055);
INSERT INTO "city" ("name","population") VALUES ('Joliet',106221);
INSERT INTO "city" ("name","population") VALUES ('Kansas City',441545);
INSERT INTO "city" ("name","population") VALUES ('Kansas City',146866);
INSERT INTO "city" ("name","population") VALUES ('Kenosha',89447);
INSERT INTO "city" ("name","population") VALUES ('Knoxville',173890);
INSERT INTO "city" ("name","population") VALUES ('Lafayette',110257);
INSERT INTO "city" ("name","population") VALUES ('Lakewood',144126);
INSERT INTO "city" ("name","population") VALUES ('Lancaster',118718);
INSERT INTO "city" ("name","population") VALUES ('Lansing',119128);
INSERT INTO "city" ("name","population") VALUES ('Laredo',176576);
INSERT INTO "city" ("name","population") VALUES ('Las Vegas',478434);
INSERT INTO "city" ("name","population") VALUES ('Lexington-Fayette',260512);
INSERT INTO "city" ("name","population") VALUES ('Lincoln',225581);
INSERT INTO "city" ("name","population") VALUES ('Little Rock',183133);
INSERT INTO "city" ("name","population") VALUES ('Livonia',100545);
INSERT INTO "city" ("name","population") VALUES ('Long Beach',461522);
INSERT INTO "city" ("name","population") VALUES ('Los Angeles',3694820);
INSERT INTO "city" ("name","population") VALUES ('Louisville',256231);
INSERT INTO "city" ("name","population") VALUES ('Lowell',105167);
INSERT INTO "city" ("name","population") VALUES ('Lubbock',199564);
INSERT INTO "city" ("name","population") VALUES ('Macon',113336);
INSERT INTO "city" ("name","population") VALUES ('Madison',208054);
INSERT INTO "city" ("name","population") VALUES ('Manchester',107006);
INSERT INTO "city" ("name","population") VALUES ('McAllen',106414);
INSERT INTO "city" ("name","population") VALUES ('Memphis',650100);
INSERT INTO "city" ("name","population") VALUES ('Mesa',396375);
INSERT INTO "city" ("name","population") VALUES ('Mesquite',124523);
INSERT INTO "city" ("name","population") VALUES ('Metairie',149428);
INSERT INTO "city" ("name","population") VALUES ('Miami',362470);
INSERT INTO "city" ("name","population") VALUES ('Miami Beach',97855);
INSERT INTO "city" ("name","population") VALUES ('Midland',98293);
INSERT INTO "city" ("name","population") VALUES ('Milwaukee',596974);
INSERT INTO "city" ("name","population") VALUES ('Minneapolis',382618);
INSERT INTO "city" ("name","population") VALUES ('Mission Viejo',98049);
INSERT INTO "city" ("name","population") VALUES ('Mobile',198915);
INSERT INTO "city" ("name","population") VALUES ('Modesto',188856);
INSERT INTO "city" ("name","population") VALUES ('Montgomery',201568);
INSERT INTO "city" ("name","population") VALUES ('Moreno Valley',142381);
INSERT INTO "city" ("name","population") VALUES ('Naperville',128358);
INSERT INTO "city" ("name","population") VALUES ('Nashville-Davidson',569891);
INSERT INTO "city" ("name","population") VALUES ('New Bedford',94780);
INSERT INTO "city" ("name","population") VALUES ('New Haven',123626);
INSERT INTO "city" ("name","population") VALUES ('New Orleans',484674);
INSERT INTO "city" ("name","population") VALUES ('New York',8008278);
INSERT INTO "city" ("name","population") VALUES ('Newark',273546);
INSERT INTO "city" ("name","population") VALUES ('Newport News',180150);
INSERT INTO "city" ("name","population") VALUES ('Norfolk',234403);
INSERT INTO "city" ("name","population") VALUES ('Norman',94193);
INSERT INTO "city" ("name","population") VALUES ('North Las Vegas',115488);
INSERT INTO "city" ("name","population") VALUES ('Norwalk',103298);
INSERT INTO "city" ("name","population") VALUES ('Oakland',399484);
INSERT INTO "city" ("name","population") VALUES ('Oceanside',161029);
INSERT INTO "city" ("name","population") VALUES ('Odessa',89293);
INSERT INTO "city" ("name","population") VALUES ('Oklahoma City',506132);
INSERT INTO "city" ("name","population") VALUES ('Omaha',390007);
INSERT INTO "city" ("name","population") VALUES ('Ontario',158007);
INSERT INTO "city" ("name","population") VALUES ('Orange',128821);
INSERT INTO "city" ("name","population") VALUES ('Orlando',185951);
INSERT INTO "city" ("name","population") VALUES ('Overland Park',149080);
INSERT INTO "city" ("name","population") VALUES ('Oxnard',170358);
INSERT INTO "city" ("name","population") VALUES ('Palmdale',116670);
INSERT INTO "city" ("name","population") VALUES ('Paradise',124682);
INSERT INTO "city" ("name","population") VALUES ('Pasadena',141674);
INSERT INTO "city" ("name","population") VALUES ('Pasadena',133936);
INSERT INTO "city" ("name","population") VALUES ('Paterson',149222);
INSERT INTO "city" ("name","population") VALUES ('Pembroke Pines',137427);
INSERT INTO "city" ("name","population") VALUES ('Peoria',112936);
INSERT INTO "city" ("name","population") VALUES ('Peoria',108364);
INSERT INTO "city" ("name","population") VALUES ('Philadelphia',1517550);
INSERT INTO "city" ("name","population") VALUES ('Phoenix',1321045);
INSERT INTO "city" ("name","population") VALUES ('Pittsburgh',334563);
INSERT INTO "city" ("name","population") VALUES ('Plano',222030);
INSERT INTO "city" ("name","population") VALUES ('Pomona',149473);
INSERT INTO "city" ("name","population") VALUES ('Portland',529121);
INSERT INTO "city" ("name","population") VALUES ('Portsmouth',100565);
INSERT INTO "city" ("name","population") VALUES ('Providence',173618);
INSERT INTO "city" ("name","population") VALUES ('Provo',105166);
INSERT INTO "city" ("name","population") VALUES ('Pueblo',102121);
INSERT INTO "city" ("name","population") VALUES ('Raleigh',276093);
INSERT INTO "city" ("name","population") VALUES ('Rancho Cucamonga',127743);
INSERT INTO "city" ("name","population") VALUES ('Reno',180480);
INSERT INTO "city" ("name","population") VALUES ('Richmond',197790);
INSERT INTO "city" ("name","population") VALUES ('Richmond',94100);
INSERT INTO "city" ("name","population") VALUES ('Riverside',255166);
INSERT INTO "city" ("name","population") VALUES ('Roanoke',93357);
INSERT INTO "city" ("name","population") VALUES ('Rochester',219773);
INSERT INTO "city" ("name","population") VALUES ('Rockford',150115);
INSERT INTO "city" ("name","population") VALUES ('Sacramento',407018);
INSERT INTO "city" ("name","population") VALUES ('Saint Louis',348189);
INSERT INTO "city" ("name","population") VALUES ('Saint Paul',287151);
INSERT INTO "city" ("name","population") VALUES ('Saint Petersburg',248232);
INSERT INTO "city" ("name","population") VALUES ('Salem',136924);
INSERT INTO "city" ("name","population") VALUES ('Salinas',151060);
INSERT INTO "city" ("name","population") VALUES ('Salt Lake City',181743);
INSERT INTO "city" ("name","population") VALUES ('San Antonio',1144646);
INSERT INTO "city" ("name","population") VALUES ('San Bernardino',185401);
INSERT INTO "city" ("name","population") VALUES ('San Buenaventura',100916);
INSERT INTO "city" ("name","population") VALUES ('San Diego',1223400);
INSERT INTO "city" ("name","population") VALUES ('San Francisco',776733);
INSERT INTO "city" ("name","population") VALUES ('San Jose',894943);
INSERT INTO "city" ("name","population") VALUES ('San Mateo',91799);
INSERT INTO "city" ("name","population") VALUES ('Sandy',101853);
INSERT INTO "city" ("name","population") VALUES ('Santa Ana',337977);
INSERT INTO "city" ("name","population") VALUES ('Santa Clara',102361);
INSERT INTO "city" ("name","population") VALUES ('Santa Clarita',151088);
INSERT INTO "city" ("name","population") VALUES ('Santa Monica',91084);
INSERT INTO "city" ("name","population") VALUES ('Santa Rosa',147595);
INSERT INTO "city" ("name","population") VALUES ('Savannah',131510);
INSERT INTO "city" ("name","population") VALUES ('Scottsdale',202705);
INSERT INTO "city" ("name","population") VALUES ('Seattle',563374);
INSERT INTO "city" ("name","population") VALUES ('Shreveport',200145);
INSERT INTO "city" ("name","population") VALUES ('Simi Valley',111351);
INSERT INTO "city" ("name","population") VALUES ('Sioux Falls',123975);
INSERT INTO "city" ("name","population") VALUES ('South Bend',107789);
INSERT INTO "city" ("name","population") VALUES ('Spokane',195629);
INSERT INTO "city" ("name","population") VALUES ('Springfield',152082);
INSERT INTO "city" ("name","population") VALUES ('Springfield',151580);
INSERT INTO "city" ("name","population") VALUES ('Springfield',111454);
INSERT INTO "city" ("name","population") VALUES ('Stamford',117083);
INSERT INTO "city" ("name","population") VALUES ('Sterling Heights',124471);
INSERT INTO "city" ("name","population") VALUES ('Stockton',243771);
INSERT INTO "city" ("name","population") VALUES ('Sunnyvale',131760);
INSERT INTO "city" ("name","population") VALUES ('Sunrise Manor',95362);
INSERT INTO "city" ("name","population") VALUES ('Syracuse',147306);
INSERT INTO "city" ("name","population") VALUES ('Tacoma',193556);
INSERT INTO "city" ("name","population") VALUES ('Tallahassee',150624);
INSERT INTO "city" ("name","population") VALUES ('Tampa',303447);
INSERT INTO "city" ("name","population") VALUES ('Tempe',158625);
INSERT INTO "city" ("name","population") VALUES ('Thousand Oaks',117005);
INSERT INTO "city" ("name","population") VALUES ('Toledo',313619);
INSERT INTO "city" ("name","population") VALUES ('Topeka',122377);
INSERT INTO "city" ("name","population") VALUES ('Torrance',137946);
INSERT INTO "city" ("name","population") VALUES ('Tucson',486699);
INSERT INTO "city" ("name","population") VALUES ('Tulsa',393049);
INSERT INTO "city" ("name","population") VALUES ('Vallejo',116760);
INSERT INTO "city" ("name","population") VALUES ('Vancouver',143560);
INSERT INTO "city" ("name","population") VALUES ('Virginia Beach',425257);
INSERT INTO "city" ("name","population") VALUES ('Visalia',91762);
INSERT INTO "city" ("name","population") VALUES ('Waco',113726);
INSERT INTO "city" ("name","population") VALUES ('Warren',138247);
INSERT INTO "city" ("name","population") VALUES ('Washington',572059);
INSERT INTO "city" ("name","population") VALUES ('Waterbury',107271);
INSERT INTO "city" ("name","population") VALUES ('West Covina',105080);
INSERT INTO "city" ("name","population") VALUES ('West Valley City',108896);
INSERT INTO "city" ("name","population") VALUES ('Westminster',100940);
INSERT INTO "city" ("name","population") VALUES ('Wichita',344284);
INSERT INTO "city" ("name","population") VALUES ('Wichita Falls',104197);
INSERT INTO "city" ("name","population") VALUES ('Winston-Salem',185776);
INSERT INTO "city" ("name","population") VALUES ('Worcester',172648);
INSERT INTO "city" ("name","population") VALUES ('Yonkers',196086);
COMMIT;
