BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "albums" (
	"AlbumId"	INTEGER NOT NULL,
	"Title"	NVARCHAR(160) NOT NULL,
	"ArtistId"	INTEGER NOT NULL,
	FOREIGN KEY("ArtistId") REFERENCES "artists"("ArtistId") ON DELETE NO ACTION ON UPDATE NO ACTION,
	PRIMARY KEY("AlbumId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "artists" (
	"ArtistId"	INTEGER NOT NULL,
	"Name"	NVARCHAR(120),
	PRIMARY KEY("ArtistId" AUTOINCREMENT)
);
INSERT INTO "albums" VALUES (1,'For Those About To Rock We Salute You',1);
INSERT INTO "albums" VALUES (2,'Balls to the Wall',2);
INSERT INTO "albums" VALUES (3,'Restless and Wild',2);
INSERT INTO "albums" VALUES (4,'Let There Be Rock',1);
INSERT INTO "albums" VALUES (5,'Big Ones',3);
INSERT INTO "albums" VALUES (6,'Jagged Little Pill',4);
INSERT INTO "albums" VALUES (7,'Facelift',5);
INSERT INTO "albums" VALUES (8,'Warner 25 Anos',6);
INSERT INTO "albums" VALUES (9,'Plays Metallica By Four Cellos',7);
INSERT INTO "albums" VALUES (10,'Audioslave',8);
INSERT INTO "albums" VALUES (11,'Out Of Exile',8);
INSERT INTO "albums" VALUES (12,'BackBeat Soundtrack',9);
INSERT INTO "albums" VALUES (13,'The Best Of Billy Cobham',10);
INSERT INTO "albums" VALUES (14,'Alcohol Fueled Brewtality Live! [Disc 1]',11);
INSERT INTO "albums" VALUES (15,'Alcohol Fueled Brewtality Live! [Disc 2]',11);
INSERT INTO "albums" VALUES (16,'Black Sabbath',12);
INSERT INTO "albums" VALUES (17,'Black Sabbath Vol. 4 (Remaster)',12);
INSERT INTO "albums" VALUES (18,'Body Count',13);
INSERT INTO "albums" VALUES (19,'Chemical Wedding',14);
INSERT INTO "albums" VALUES (20,'The Best Of Buddy Guy - The Millenium Collection',15);
INSERT INTO "albums" VALUES (21,'Prenda Minha',16);
INSERT INTO "albums" VALUES (22,'Sozinho Remix Ao Vivo',16);
INSERT INTO "albums" VALUES (23,'Minha Historia',17);
INSERT INTO "albums" VALUES (24,'Afrociberdelia',18);
INSERT INTO "albums" VALUES (25,'Da Lama Ao Caos',18);
INSERT INTO "albums" VALUES (26,'Acústico MTV [Live]',19);
INSERT INTO "albums" VALUES (27,'Cidade Negra - Hits',19);
INSERT INTO "albums" VALUES (28,'Na Pista',20);
INSERT INTO "albums" VALUES (29,'Axé Bahia 2001',21);
INSERT INTO "albums" VALUES (30,'BBC Sessions [Disc 1] [Live]',22);
INSERT INTO "albums" VALUES (31,'Bongo Fury',23);
INSERT INTO "albums" VALUES (32,'Carnaval 2001',21);
INSERT INTO "albums" VALUES (33,'Chill: Brazil (Disc 1)',24);
INSERT INTO "albums" VALUES (34,'Chill: Brazil (Disc 2)',6);
INSERT INTO "albums" VALUES (35,'Garage Inc. (Disc 1)',50);
INSERT INTO "albums" VALUES (36,'Greatest Hits II',51);
INSERT INTO "albums" VALUES (37,'Greatest Kiss',52);
INSERT INTO "albums" VALUES (38,'Heart of the Night',53);
INSERT INTO "albums" VALUES (39,'International Superhits',54);
INSERT INTO "albums" VALUES (40,'Into The Light',55);
INSERT INTO "albums" VALUES (41,'Meus Momentos',56);
INSERT INTO "albums" VALUES (42,'Minha História',57);
INSERT INTO "albums" VALUES (43,'MK III The Final Concerts [Disc 1]',58);
INSERT INTO "albums" VALUES (44,'Physical Graffiti [Disc 1]',22);
INSERT INTO "albums" VALUES (45,'Sambas De Enredo 2001',21);
INSERT INTO "albums" VALUES (46,'Supernatural',59);
INSERT INTO "albums" VALUES (47,'The Best of Ed Motta',37);
INSERT INTO "albums" VALUES (48,'The Essential Miles Davis [Disc 1]',68);
INSERT INTO "albums" VALUES (49,'The Essential Miles Davis [Disc 2]',68);
INSERT INTO "albums" VALUES (50,'The Final Concerts (Disc 2)',58);
INSERT INTO "albums" VALUES (51,'Up An'' Atom',69);
INSERT INTO "albums" VALUES (52,'Vinícius De Moraes - Sem Limite',70);
INSERT INTO "albums" VALUES (53,'Vozes do MPB',21);
INSERT INTO "albums" VALUES (54,'Chronicle, Vol. 1',76);
INSERT INTO "albums" VALUES (55,'Chronicle, Vol. 2',76);
INSERT INTO "albums" VALUES (56,'Cássia Eller - Coleção Sem Limite [Disc 2]',77);
INSERT INTO "albums" VALUES (57,'Cássia Eller - Sem Limite [Disc 1]',77);
INSERT INTO "albums" VALUES (58,'Come Taste The Band',58);
INSERT INTO "albums" VALUES (59,'Deep Purple In Rock',58);
INSERT INTO "albums" VALUES (60,'Fireball',58);
INSERT INTO "albums" VALUES (61,'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s',58);
INSERT INTO "albums" VALUES (62,'Machine Head',58);
INSERT INTO "albums" VALUES (63,'Purpendicular',58);
INSERT INTO "albums" VALUES (64,'Slaves And Masters',58);
INSERT INTO "albums" VALUES (65,'Stormbringer',58);
INSERT INTO "albums" VALUES (66,'The Battle Rages On',58);
INSERT INTO "albums" VALUES (67,'Vault: Def Leppard''s Greatest Hits',78);
INSERT INTO "albums" VALUES (68,'Outbreak',79);
INSERT INTO "albums" VALUES (69,'Djavan Ao Vivo - Vol. 02',80);
INSERT INTO "albums" VALUES (70,'Djavan Ao Vivo - Vol. 1',80);
INSERT INTO "albums" VALUES (71,'Elis Regina-Minha História',41);
INSERT INTO "albums" VALUES (72,'The Cream Of Clapton',81);
INSERT INTO "albums" VALUES (73,'Unplugged',81);
INSERT INTO "albums" VALUES (74,'Album Of The Year',82);
INSERT INTO "albums" VALUES (75,'Angel Dust',82);
INSERT INTO "albums" VALUES (76,'King For A Day Fool For A Lifetime',82);
INSERT INTO "albums" VALUES (77,'The Real Thing',82);
INSERT INTO "albums" VALUES (78,'Deixa Entrar',83);
INSERT INTO "albums" VALUES (79,'In Your Honor [Disc 1]',84);
INSERT INTO "albums" VALUES (80,'In Your Honor [Disc 2]',84);
INSERT INTO "albums" VALUES (81,'One By One',84);
INSERT INTO "albums" VALUES (82,'The Colour And The Shape',84);
INSERT INTO "albums" VALUES (83,'My Way: The Best Of Frank Sinatra [Disc 1]',85);
INSERT INTO "albums" VALUES (84,'Roda De Funk',86);
INSERT INTO "albums" VALUES (85,'As Canções de Eu Tu Eles',27);
INSERT INTO "albums" VALUES (86,'Quanta Gente Veio Ver (Live)',27);
INSERT INTO "albums" VALUES (87,'Quanta Gente Veio ver--Bônus De Carnaval',27);
INSERT INTO "albums" VALUES (88,'Faceless',87);
INSERT INTO "albums" VALUES (89,'American Idiot',54);
INSERT INTO "albums" VALUES (90,'Appetite for Destruction',88);
INSERT INTO "albums" VALUES (91,'Use Your Illusion I',88);
INSERT INTO "albums" VALUES (92,'Use Your Illusion II',88);
INSERT INTO "albums" VALUES (93,'Blue Moods',89);
INSERT INTO "albums" VALUES (94,'A Matter of Life and Death',90);
INSERT INTO "albums" VALUES (95,'A Real Dead One',90);
INSERT INTO "albums" VALUES (96,'A Real Live One',90);
INSERT INTO "albums" VALUES (97,'Brave New World',90);
INSERT INTO "albums" VALUES (98,'Dance Of Death',90);
INSERT INTO "albums" VALUES (99,'Fear Of The Dark',90);
INSERT INTO "albums" VALUES (100,'Iron Maiden',90);
INSERT INTO "albums" VALUES (101,'Killers',90);
INSERT INTO "albums" VALUES (102,'Live After Death',90);
INSERT INTO "albums" VALUES (103,'Live At Donington 1992 (Disc 1)',90);
INSERT INTO "albums" VALUES (104,'Live At Donington 1992 (Disc 2)',90);
INSERT INTO "albums" VALUES (105,'No Prayer For The Dying',90);
INSERT INTO "albums" VALUES (106,'Piece Of Mind',90);
INSERT INTO "albums" VALUES (107,'Powerslave',90);
INSERT INTO "albums" VALUES (108,'Rock In Rio [CD1]',90);
INSERT INTO "albums" VALUES (109,'Rock In Rio [CD2]',90);
INSERT INTO "albums" VALUES (110,'Seventh Son of a Seventh Son',90);
INSERT INTO "albums" VALUES (111,'Somewhere in Time',90);
INSERT INTO "albums" VALUES (112,'The Number of The Beast',90);
INSERT INTO "albums" VALUES (113,'The X Factor',90);
INSERT INTO "albums" VALUES (114,'Virtual XI',90);
INSERT INTO "albums" VALUES (115,'Sex Machine',91);
INSERT INTO "albums" VALUES (116,'Emergency On Planet Earth',92);
INSERT INTO "albums" VALUES (117,'Synkronized',92);
INSERT INTO "albums" VALUES (118,'The Return Of The Space Cowboy',92);
INSERT INTO "albums" VALUES (119,'Get Born',93);
INSERT INTO "albums" VALUES (120,'Are You Experienced?',94);
INSERT INTO "albums" VALUES (121,'Surfing with the Alien (Remastered)',95);
INSERT INTO "albums" VALUES (122,'Jorge Ben Jor 25 Anos',46);
INSERT INTO "albums" VALUES (123,'Jota Quest-1995',96);
INSERT INTO "albums" VALUES (124,'Cafezinho',97);
INSERT INTO "albums" VALUES (125,'Living After Midnight',98);
INSERT INTO "albums" VALUES (126,'Unplugged [Live]',52);
INSERT INTO "albums" VALUES (127,'BBC Sessions [Disc 2] [Live]',22);
INSERT INTO "albums" VALUES (128,'Coda',22);
INSERT INTO "albums" VALUES (129,'Houses Of The Holy',22);
INSERT INTO "albums" VALUES (130,'In Through The Out Door',22);
INSERT INTO "albums" VALUES (131,'IV',22);
INSERT INTO "albums" VALUES (132,'Led Zeppelin I',22);
INSERT INTO "albums" VALUES (133,'Led Zeppelin II',22);
INSERT INTO "albums" VALUES (134,'Led Zeppelin III',22);
INSERT INTO "albums" VALUES (135,'Physical Graffiti [Disc 2]',22);
INSERT INTO "albums" VALUES (136,'Presence',22);
INSERT INTO "albums" VALUES (137,'The Song Remains The Same (Disc 1)',22);
INSERT INTO "albums" VALUES (138,'The Song Remains The Same (Disc 2)',22);
INSERT INTO "albums" VALUES (139,'A TempestadeTempestade Ou O Livro Dos Dias',99);
INSERT INTO "albums" VALUES (140,'Mais Do Mesmo',99);
INSERT INTO "albums" VALUES (141,'Greatest Hits',100);
INSERT INTO "albums" VALUES (142,'Lulu Santos - RCA 100 Anos De Música - Álbum 01',101);
INSERT INTO "albums" VALUES (143,'Lulu Santos - RCA 100 Anos De Música - Álbum 02',101);
INSERT INTO "albums" VALUES (144,'Misplaced Childhood',102);
INSERT INTO "albums" VALUES (145,'Barulhinho Bom',103);
INSERT INTO "albums" VALUES (146,'Seek And Shall Find: More Of The Best (1963-1981)',104);
INSERT INTO "albums" VALUES (147,'The Best Of Men At Work',105);
INSERT INTO "albums" VALUES (148,'Black Album',50);
INSERT INTO "albums" VALUES (149,'Garage Inc. (Disc 2)',50);
INSERT INTO "albums" VALUES (150,'Kill ''Em All',50);
INSERT INTO "albums" VALUES (151,'Load',50);
INSERT INTO "albums" VALUES (152,'Master Of Puppets',50);
INSERT INTO "albums" VALUES (153,'ReLoad',50);
INSERT INTO "albums" VALUES (154,'Ride The Lightning',50);
INSERT INTO "albums" VALUES (155,'St. Anger',50);
INSERT INTO "albums" VALUES (156,'...And Justice For All',50);
INSERT INTO "albums" VALUES (157,'Miles Ahead',68);
INSERT INTO "albums" VALUES (158,'Milton Nascimento Ao Vivo',42);
INSERT INTO "albums" VALUES (159,'Minas',42);
INSERT INTO "albums" VALUES (160,'Ace Of Spades',106);
INSERT INTO "albums" VALUES (161,'Demorou...',108);
INSERT INTO "albums" VALUES (162,'Motley Crue Greatest Hits',109);
INSERT INTO "albums" VALUES (163,'From The Muddy Banks Of The Wishkah [Live]',110);
INSERT INTO "albums" VALUES (164,'Nevermind',110);
INSERT INTO "albums" VALUES (165,'Compositores',111);
INSERT INTO "albums" VALUES (166,'Olodum',112);
INSERT INTO "albums" VALUES (167,'Acústico MTV',113);
INSERT INTO "albums" VALUES (168,'Arquivo II',113);
INSERT INTO "albums" VALUES (169,'Arquivo Os Paralamas Do Sucesso',113);
INSERT INTO "albums" VALUES (170,'Bark at the Moon (Remastered)',114);
INSERT INTO "albums" VALUES (171,'Blizzard of Ozz',114);
INSERT INTO "albums" VALUES (172,'Diary of a Madman (Remastered)',114);
INSERT INTO "albums" VALUES (173,'No More Tears (Remastered)',114);
INSERT INTO "albums" VALUES (174,'Tribute',114);
INSERT INTO "albums" VALUES (175,'Walking Into Clarksdale',115);
INSERT INTO "albums" VALUES (176,'Original Soundtracks 1',116);
INSERT INTO "albums" VALUES (177,'The Beast Live',117);
INSERT INTO "albums" VALUES (178,'Live On Two Legs [Live]',118);
INSERT INTO "albums" VALUES (179,'Pearl Jam',118);
INSERT INTO "albums" VALUES (180,'Riot Act',118);
INSERT INTO "albums" VALUES (181,'Ten',118);
INSERT INTO "albums" VALUES (182,'Vs.',118);
INSERT INTO "albums" VALUES (183,'Dark Side Of The Moon',120);
INSERT INTO "albums" VALUES (184,'Os Cães Ladram Mas A Caravana Não Pára',121);
INSERT INTO "albums" VALUES (185,'Greatest Hits I',51);
INSERT INTO "albums" VALUES (186,'News Of The World',51);
INSERT INTO "albums" VALUES (187,'Out Of Time',122);
INSERT INTO "albums" VALUES (188,'Green',124);
INSERT INTO "albums" VALUES (189,'New Adventures In Hi-Fi',124);
INSERT INTO "albums" VALUES (190,'The Best Of R.E.M.: The IRS Years',124);
INSERT INTO "albums" VALUES (191,'Cesta Básica',125);
INSERT INTO "albums" VALUES (192,'Raul Seixas',126);
INSERT INTO "albums" VALUES (193,'Blood Sugar Sex Magik',127);
INSERT INTO "albums" VALUES (194,'By The Way',127);
INSERT INTO "albums" VALUES (195,'Californication',127);
INSERT INTO "albums" VALUES (196,'Retrospective I (1974-1980)',128);
INSERT INTO "albums" VALUES (197,'Santana - As Years Go By',59);
INSERT INTO "albums" VALUES (198,'Santana Live',59);
INSERT INTO "albums" VALUES (199,'Maquinarama',130);
INSERT INTO "albums" VALUES (200,'O Samba Poconé',130);
INSERT INTO "albums" VALUES (201,'Judas 0: B-Sides and Rarities',131);
INSERT INTO "albums" VALUES (202,'Rotten Apples: Greatest Hits',131);
INSERT INTO "albums" VALUES (203,'A-Sides',132);
INSERT INTO "albums" VALUES (204,'Morning Dance',53);
INSERT INTO "albums" VALUES (205,'In Step',133);
INSERT INTO "albums" VALUES (206,'Core',134);
INSERT INTO "albums" VALUES (207,'Mezmerize',135);
INSERT INTO "albums" VALUES (208,'[1997] Black Light Syndrome',136);
INSERT INTO "albums" VALUES (209,'Live [Disc 1]',137);
INSERT INTO "albums" VALUES (210,'Live [Disc 2]',137);
INSERT INTO "albums" VALUES (211,'The Singles',138);
INSERT INTO "albums" VALUES (212,'Beyond Good And Evil',139);
INSERT INTO "albums" VALUES (213,'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]',139);
INSERT INTO "albums" VALUES (214,'The Doors',140);
INSERT INTO "albums" VALUES (215,'The Police Greatest Hits',141);
INSERT INTO "albums" VALUES (216,'Hot Rocks, 1964-1971 (Disc 1)',142);
INSERT INTO "albums" VALUES (217,'No Security',142);
INSERT INTO "albums" VALUES (218,'Voodoo Lounge',142);
INSERT INTO "albums" VALUES (219,'Tangents',143);
INSERT INTO "albums" VALUES (220,'Transmission',143);
INSERT INTO "albums" VALUES (221,'My Generation - The Very Best Of The Who',144);
INSERT INTO "albums" VALUES (222,'Serie Sem Limite (Disc 1)',145);
INSERT INTO "albums" VALUES (223,'Serie Sem Limite (Disc 2)',145);
INSERT INTO "albums" VALUES (224,'Acústico',146);
INSERT INTO "albums" VALUES (225,'Volume Dois',146);
INSERT INTO "albums" VALUES (226,'Battlestar Galactica: The Story So Far',147);
INSERT INTO "albums" VALUES (227,'Battlestar Galactica, Season 3',147);
INSERT INTO "albums" VALUES (228,'Heroes, Season 1',148);
INSERT INTO "albums" VALUES (229,'Lost, Season 3',149);
INSERT INTO "albums" VALUES (230,'Lost, Season 1',149);
INSERT INTO "albums" VALUES (231,'Lost, Season 2',149);
INSERT INTO "albums" VALUES (232,'Achtung Baby',150);
INSERT INTO "albums" VALUES (233,'All That You Can''t Leave Behind',150);
INSERT INTO "albums" VALUES (234,'B-Sides 1980-1990',150);
INSERT INTO "albums" VALUES (235,'How To Dismantle An Atomic Bomb',150);
INSERT INTO "albums" VALUES (236,'Pop',150);
INSERT INTO "albums" VALUES (237,'Rattle And Hum',150);
INSERT INTO "albums" VALUES (238,'The Best Of 1980-1990',150);
INSERT INTO "albums" VALUES (239,'War',150);
INSERT INTO "albums" VALUES (240,'Zooropa',150);
INSERT INTO "albums" VALUES (241,'UB40 The Best Of - Volume Two [UK]',151);
INSERT INTO "albums" VALUES (242,'Diver Down',152);
INSERT INTO "albums" VALUES (243,'The Best Of Van Halen, Vol. I',152);
INSERT INTO "albums" VALUES (244,'Van Halen',152);
INSERT INTO "albums" VALUES (245,'Van Halen III',152);
INSERT INTO "albums" VALUES (246,'Contraband',153);
INSERT INTO "albums" VALUES (247,'Vinicius De Moraes',72);
INSERT INTO "albums" VALUES (248,'Ao Vivo [IMPORT]',155);
INSERT INTO "albums" VALUES (249,'The Office, Season 1',156);
INSERT INTO "albums" VALUES (250,'The Office, Season 2',156);
INSERT INTO "albums" VALUES (251,'The Office, Season 3',156);
INSERT INTO "albums" VALUES (252,'Un-Led-Ed',157);
INSERT INTO "albums" VALUES (253,'Battlestar Galactica (Classic), Season 1',158);
INSERT INTO "albums" VALUES (254,'Aquaman',159);
INSERT INTO "albums" VALUES (255,'Instant Karma: The Amnesty International Campaign to Save Darfur',150);
INSERT INTO "albums" VALUES (256,'Speak of the Devil',114);
INSERT INTO "albums" VALUES (257,'20th Century Masters - The Millennium Collection: The Best of Scorpions',179);
INSERT INTO "albums" VALUES (258,'House of Pain',180);
INSERT INTO "albums" VALUES (259,'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro',36);
INSERT INTO "albums" VALUES (260,'Cake: B-Sides and Rarities',196);
INSERT INTO "albums" VALUES (261,'LOST, Season 4',149);
INSERT INTO "albums" VALUES (262,'Quiet Songs',197);
INSERT INTO "albums" VALUES (263,'Muso Ko',198);
INSERT INTO "albums" VALUES (264,'Realize',199);
INSERT INTO "albums" VALUES (265,'Every Kind of Light',200);
INSERT INTO "albums" VALUES (266,'Duos II',201);
INSERT INTO "albums" VALUES (267,'Worlds',202);
INSERT INTO "albums" VALUES (268,'The Best of Beethoven',203);
INSERT INTO "albums" VALUES (269,'Temple of the Dog',204);
INSERT INTO "albums" VALUES (270,'Carry On',205);
INSERT INTO "albums" VALUES (271,'Revelations',8);
INSERT INTO "albums" VALUES (272,'Adorate Deum: Gregorian Chant from the Proper of the Mass',206);
INSERT INTO "albums" VALUES (273,'Allegri: Miserere',207);
INSERT INTO "albums" VALUES (274,'Pachelbel: Canon & Gigue',208);
INSERT INTO "albums" VALUES (275,'Vivaldi: The Four Seasons',209);
INSERT INTO "albums" VALUES (276,'Bach: Violin Concertos',210);
INSERT INTO "albums" VALUES (277,'Bach: Goldberg Variations',211);
INSERT INTO "albums" VALUES (278,'Bach: The Cello Suites',212);
INSERT INTO "albums" VALUES (279,'Handel: The Messiah (Highlights)',213);
INSERT INTO "albums" VALUES (280,'The World of Classical Favourites',214);
INSERT INTO "albums" VALUES (281,'Sir Neville Marriner: A Celebration',215);
INSERT INTO "albums" VALUES (282,'Mozart: Wind Concertos',216);
INSERT INTO "albums" VALUES (283,'Haydn: Symphonies 99 - 104',217);
INSERT INTO "albums" VALUES (284,'Beethoven: Symhonies Nos. 5 & 6',218);
INSERT INTO "albums" VALUES (285,'A Soprano Inspired',219);
INSERT INTO "albums" VALUES (286,'Great Opera Choruses',220);
INSERT INTO "albums" VALUES (287,'Wagner: Favourite Overtures',221);
INSERT INTO "albums" VALUES (288,'Fauré: Requiem, Ravel: Pavane & Others',222);
INSERT INTO "albums" VALUES (289,'Tchaikovsky: The Nutcracker',223);
INSERT INTO "albums" VALUES (290,'The Last Night of the Proms',224);
INSERT INTO "albums" VALUES (291,'Puccini: Madama Butterfly - Highlights',225);
INSERT INTO "albums" VALUES (292,'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies',226);
INSERT INTO "albums" VALUES (293,'Pavarotti''s Opera Made Easy',227);
INSERT INTO "albums" VALUES (294,'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings',228);
INSERT INTO "albums" VALUES (295,'Carmina Burana',229);
INSERT INTO "albums" VALUES (296,'A Copland Celebration, Vol. I',230);
INSERT INTO "albums" VALUES (297,'Bach: Toccata & Fugue in D Minor',231);
INSERT INTO "albums" VALUES (298,'Prokofiev: Symphony No.1',232);
INSERT INTO "albums" VALUES (299,'Scheherazade',233);
INSERT INTO "albums" VALUES (300,'Bach: The Brandenburg Concertos',234);
INSERT INTO "albums" VALUES (301,'Chopin: Piano Concertos Nos. 1 & 2',235);
INSERT INTO "albums" VALUES (302,'Mascagni: Cavalleria Rusticana',236);
INSERT INTO "albums" VALUES (303,'Sibelius: Finlandia',237);
INSERT INTO "albums" VALUES (304,'Beethoven Piano Sonatas: Moonlight & Pastorale',238);
INSERT INTO "albums" VALUES (305,'Great Recordings of the Century - Mahler: Das Lied von der Erde',240);
INSERT INTO "albums" VALUES (306,'Elgar: Cello Concerto & Vaughan Williams: Fantasias',241);
INSERT INTO "albums" VALUES (307,'Adams, John: The Chairman Dances',242);
INSERT INTO "albums" VALUES (308,'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory',243);
INSERT INTO "albums" VALUES (309,'Palestrina: Missa Papae Marcelli & Allegri: Miserere',244);
INSERT INTO "albums" VALUES (310,'Prokofiev: Romeo & Juliet',245);
INSERT INTO "albums" VALUES (311,'Strauss: Waltzes',226);
INSERT INTO "albums" VALUES (312,'Berlioz: Symphonie Fantastique',245);
INSERT INTO "albums" VALUES (313,'Bizet: Carmen Highlights',246);
INSERT INTO "albums" VALUES (314,'English Renaissance',247);
INSERT INTO "albums" VALUES (315,'Handel: Music for the Royal Fireworks (Original Version 1749)',208);
INSERT INTO "albums" VALUES (316,'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande',248);
INSERT INTO "albums" VALUES (317,'Mozart Gala: Famous Arias',249);
INSERT INTO "albums" VALUES (318,'SCRIABIN: Vers la flamme',250);
INSERT INTO "albums" VALUES (319,'Armada: Music from the Courts of England and Spain',251);
INSERT INTO "albums" VALUES (320,'Mozart: Symphonies Nos. 40 & 41',248);
INSERT INTO "albums" VALUES (321,'Back to Black',252);
INSERT INTO "albums" VALUES (322,'Frank',252);
INSERT INTO "albums" VALUES (323,'Carried to Dust (Bonus Track Version)',253);
INSERT INTO "albums" VALUES (324,'Beethoven: Symphony No. 6 ''Pastoral'' Etc.',254);
INSERT INTO "albums" VALUES (325,'Bartok: Violin & Viola Concertos',255);
INSERT INTO "albums" VALUES (326,'Mendelssohn: A Midsummer Night''s Dream',256);
INSERT INTO "albums" VALUES (327,'Bach: Orchestral Suites Nos. 1 - 4',257);
INSERT INTO "albums" VALUES (328,'Charpentier: Divertissements, Airs & Concerts',258);
INSERT INTO "albums" VALUES (329,'South American Getaway',259);
INSERT INTO "albums" VALUES (330,'Górecki: Symphony No. 3',260);
INSERT INTO "albums" VALUES (331,'Purcell: The Fairy Queen',261);
INSERT INTO "albums" VALUES (332,'The Ultimate Relexation Album',262);
INSERT INTO "albums" VALUES (333,'Purcell: Music for the Queen Mary',263);
INSERT INTO "albums" VALUES (334,'Weill: The Seven Deadly Sins',264);
INSERT INTO "albums" VALUES (335,'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro',265);
INSERT INTO "albums" VALUES (336,'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',248);
INSERT INTO "albums" VALUES (337,'Szymanowski: Piano Works, Vol. 1',266);
INSERT INTO "albums" VALUES (338,'Nielsen: The Six Symphonies',267);
INSERT INTO "albums" VALUES (339,'Great Recordings of the Century: Paganini''s 24 Caprices',268);
INSERT INTO "albums" VALUES (340,'Liszt - 12 Études D''Execution Transcendante',269);
INSERT INTO "albums" VALUES (341,'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder',270);
INSERT INTO "albums" VALUES (342,'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3',271);
INSERT INTO "albums" VALUES (343,'Respighi:Pines of Rome',226);
INSERT INTO "albums" VALUES (344,'Schubert: The Late String Quartets & String Quintet (3 CD''s)',272);
INSERT INTO "albums" VALUES (345,'Monteverdi: L''Orfeo',273);
INSERT INTO "albums" VALUES (346,'Mozart: Chamber Music',274);
INSERT INTO "albums" VALUES (347,'Koyaanisqatsi (Soundtrack from the Motion Picture)',275);
INSERT INTO "artists" VALUES (1,'AC/DC');
INSERT INTO "artists" VALUES (2,'Accept');
INSERT INTO "artists" VALUES (3,'Aerosmith');
INSERT INTO "artists" VALUES (4,'Alanis Morissette');
INSERT INTO "artists" VALUES (5,'Alice In Chains');
INSERT INTO "artists" VALUES (6,'Antônio Carlos Jobim');
INSERT INTO "artists" VALUES (7,'Apocalyptica');
INSERT INTO "artists" VALUES (8,'Audioslave');
INSERT INTO "artists" VALUES (9,'BackBeat');
INSERT INTO "artists" VALUES (10,'Billy Cobham');
INSERT INTO "artists" VALUES (11,'Black Label Society');
INSERT INTO "artists" VALUES (12,'Black Sabbath');
INSERT INTO "artists" VALUES (13,'Body Count');
INSERT INTO "artists" VALUES (14,'Bruce Dickinson');
INSERT INTO "artists" VALUES (15,'Buddy Guy');
INSERT INTO "artists" VALUES (16,'Caetano Veloso');
INSERT INTO "artists" VALUES (17,'Chico Buarque');
INSERT INTO "artists" VALUES (18,'Chico Science & Nação Zumbi');
INSERT INTO "artists" VALUES (19,'Cidade Negra');
INSERT INTO "artists" VALUES (20,'Cláudio Zoli');
INSERT INTO "artists" VALUES (21,'Various Artists');
INSERT INTO "artists" VALUES (22,'Led Zeppelin');
INSERT INTO "artists" VALUES (23,'Frank Zappa & Captain Beefheart');
INSERT INTO "artists" VALUES (24,'Marcos Valle');
INSERT INTO "artists" VALUES (25,'Milton Nascimento & Bebeto');
INSERT INTO "artists" VALUES (26,'Azymuth');
INSERT INTO "artists" VALUES (27,'Gilberto Gil');
INSERT INTO "artists" VALUES (28,'João Gilberto');
INSERT INTO "artists" VALUES (29,'Bebel Gilberto');
INSERT INTO "artists" VALUES (30,'Jorge Vercilo');
INSERT INTO "artists" VALUES (31,'Baby Consuelo');
INSERT INTO "artists" VALUES (32,'Ney Matogrosso');
INSERT INTO "artists" VALUES (33,'Luiz Melodia');
INSERT INTO "artists" VALUES (34,'Nando Reis');
INSERT INTO "artists" VALUES (35,'Pedro Luís & A Parede');
INSERT INTO "artists" VALUES (36,'O Rappa');
INSERT INTO "artists" VALUES (37,'Ed Motta');
INSERT INTO "artists" VALUES (38,'Banda Black Rio');
INSERT INTO "artists" VALUES (39,'Fernanda Porto');
INSERT INTO "artists" VALUES (40,'Os Cariocas');
INSERT INTO "artists" VALUES (41,'Elis Regina');
INSERT INTO "artists" VALUES (42,'Milton Nascimento');
INSERT INTO "artists" VALUES (43,'A Cor Do Som');
INSERT INTO "artists" VALUES (44,'Kid Abelha');
INSERT INTO "artists" VALUES (45,'Sandra De Sá');
INSERT INTO "artists" VALUES (46,'Jorge Ben');
INSERT INTO "artists" VALUES (47,'Hermeto Pascoal');
INSERT INTO "artists" VALUES (48,'Barão Vermelho');
INSERT INTO "artists" VALUES (49,'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO "artists" VALUES (50,'Metallica');
INSERT INTO "artists" VALUES (51,'Queen');
INSERT INTO "artists" VALUES (52,'Kiss');
INSERT INTO "artists" VALUES (53,'Spyro Gyra');
INSERT INTO "artists" VALUES (54,'Green Day');
INSERT INTO "artists" VALUES (55,'David Coverdale');
INSERT INTO "artists" VALUES (56,'Gonzaguinha');
INSERT INTO "artists" VALUES (57,'Os Mutantes');
INSERT INTO "artists" VALUES (58,'Deep Purple');
INSERT INTO "artists" VALUES (59,'Santana');
INSERT INTO "artists" VALUES (60,'Santana Feat. Dave Matthews');
INSERT INTO "artists" VALUES (61,'Santana Feat. Everlast');
INSERT INTO "artists" VALUES (62,'Santana Feat. Rob Thomas');
INSERT INTO "artists" VALUES (63,'Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO "artists" VALUES (64,'Santana Feat. The Project G&B');
INSERT INTO "artists" VALUES (65,'Santana Feat. Maná');
INSERT INTO "artists" VALUES (66,'Santana Feat. Eagle-Eye Cherry');
INSERT INTO "artists" VALUES (67,'Santana Feat. Eric Clapton');
INSERT INTO "artists" VALUES (68,'Miles Davis');
INSERT INTO "artists" VALUES (69,'Gene Krupa');
INSERT INTO "artists" VALUES (70,'Toquinho & Vinícius');
INSERT INTO "artists" VALUES (71,'Vinícius De Moraes & Baden Powell');
INSERT INTO "artists" VALUES (72,'Vinícius De Moraes');
INSERT INTO "artists" VALUES (73,'Vinícius E Qurteto Em Cy');
INSERT INTO "artists" VALUES (74,'Vinícius E Odette Lara');
INSERT INTO "artists" VALUES (75,'Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO "artists" VALUES (76,'Creedence Clearwater Revival');
INSERT INTO "artists" VALUES (77,'Cássia Eller');
INSERT INTO "artists" VALUES (78,'Def Leppard');
INSERT INTO "artists" VALUES (79,'Dennis Chambers');
INSERT INTO "artists" VALUES (80,'Djavan');
INSERT INTO "artists" VALUES (81,'Eric Clapton');
INSERT INTO "artists" VALUES (82,'Faith No More');
INSERT INTO "artists" VALUES (83,'Falamansa');
INSERT INTO "artists" VALUES (84,'Foo Fighters');
INSERT INTO "artists" VALUES (85,'Frank Sinatra');
INSERT INTO "artists" VALUES (86,'Funk Como Le Gusta');
INSERT INTO "artists" VALUES (87,'Godsmack');
INSERT INTO "artists" VALUES (88,'Guns N'' Roses');
INSERT INTO "artists" VALUES (89,'Incognito');
INSERT INTO "artists" VALUES (90,'Iron Maiden');
INSERT INTO "artists" VALUES (91,'James Brown');
INSERT INTO "artists" VALUES (92,'Jamiroquai');
INSERT INTO "artists" VALUES (93,'JET');
INSERT INTO "artists" VALUES (94,'Jimi Hendrix');
INSERT INTO "artists" VALUES (95,'Joe Satriani');
INSERT INTO "artists" VALUES (96,'Jota Quest');
INSERT INTO "artists" VALUES (97,'João Suplicy');
INSERT INTO "artists" VALUES (98,'Judas Priest');
INSERT INTO "artists" VALUES (99,'Legião Urbana');
INSERT INTO "artists" VALUES (100,'Lenny Kravitz');
INSERT INTO "artists" VALUES (101,'Lulu Santos');
INSERT INTO "artists" VALUES (102,'Marillion');
INSERT INTO "artists" VALUES (103,'Marisa Monte');
INSERT INTO "artists" VALUES (104,'Marvin Gaye');
INSERT INTO "artists" VALUES (105,'Men At Work');
INSERT INTO "artists" VALUES (106,'Motörhead');
INSERT INTO "artists" VALUES (107,'Motörhead & Girlschool');
INSERT INTO "artists" VALUES (108,'Mônica Marianno');
INSERT INTO "artists" VALUES (109,'Mötley Crüe');
INSERT INTO "artists" VALUES (110,'Nirvana');
INSERT INTO "artists" VALUES (111,'O Terço');
INSERT INTO "artists" VALUES (112,'Olodum');
INSERT INTO "artists" VALUES (113,'Os Paralamas Do Sucesso');
INSERT INTO "artists" VALUES (114,'Ozzy Osbourne');
INSERT INTO "artists" VALUES (115,'Page & Plant');
INSERT INTO "artists" VALUES (116,'Passengers');
INSERT INTO "artists" VALUES (117,'Paul D''Ianno');
INSERT INTO "artists" VALUES (118,'Pearl Jam');
INSERT INTO "artists" VALUES (119,'Peter Tosh');
INSERT INTO "artists" VALUES (120,'Pink Floyd');
INSERT INTO "artists" VALUES (121,'Planet Hemp');
INSERT INTO "artists" VALUES (122,'R.E.M. Feat. Kate Pearson');
INSERT INTO "artists" VALUES (123,'R.E.M. Feat. KRS-One');
INSERT INTO "artists" VALUES (124,'R.E.M.');
INSERT INTO "artists" VALUES (125,'Raimundos');
INSERT INTO "artists" VALUES (126,'Raul Seixas');
INSERT INTO "artists" VALUES (127,'Red Hot Chili Peppers');
INSERT INTO "artists" VALUES (128,'Rush');
INSERT INTO "artists" VALUES (129,'Simply Red');
INSERT INTO "artists" VALUES (130,'Skank');
INSERT INTO "artists" VALUES (131,'Smashing Pumpkins');
INSERT INTO "artists" VALUES (132,'Soundgarden');
INSERT INTO "artists" VALUES (133,'Stevie Ray Vaughan & Double Trouble');
INSERT INTO "artists" VALUES (134,'Stone Temple Pilots');
INSERT INTO "artists" VALUES (135,'System Of A Down');
INSERT INTO "artists" VALUES (136,'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO "artists" VALUES (137,'The Black Crowes');
INSERT INTO "artists" VALUES (138,'The Clash');
INSERT INTO "artists" VALUES (139,'The Cult');
INSERT INTO "artists" VALUES (140,'The Doors');
INSERT INTO "artists" VALUES (141,'The Police');
INSERT INTO "artists" VALUES (142,'The Rolling Stones');
INSERT INTO "artists" VALUES (143,'The Tea Party');
INSERT INTO "artists" VALUES (144,'The Who');
INSERT INTO "artists" VALUES (145,'Tim Maia');
INSERT INTO "artists" VALUES (146,'Titãs');
INSERT INTO "artists" VALUES (147,'Battlestar Galactica');
INSERT INTO "artists" VALUES (148,'Heroes');
INSERT INTO "artists" VALUES (149,'Lost');
INSERT INTO "artists" VALUES (150,'U2');
INSERT INTO "artists" VALUES (151,'UB40');
INSERT INTO "artists" VALUES (152,'Van Halen');
INSERT INTO "artists" VALUES (153,'Velvet Revolver');
INSERT INTO "artists" VALUES (154,'Whitesnake');
INSERT INTO "artists" VALUES (155,'Zeca Pagodinho');
INSERT INTO "artists" VALUES (156,'The Office');
INSERT INTO "artists" VALUES (157,'Dread Zeppelin');
INSERT INTO "artists" VALUES (158,'Battlestar Galactica (Classic)');
INSERT INTO "artists" VALUES (159,'Aquaman');
INSERT INTO "artists" VALUES (160,'Christina Aguilera featuring BigElf');
INSERT INTO "artists" VALUES (161,'Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO "artists" VALUES (162,'Los Lonely Boys');
INSERT INTO "artists" VALUES (163,'Corinne Bailey Rae');
INSERT INTO "artists" VALUES (164,'Dhani Harrison & Jakob Dylan');
INSERT INTO "artists" VALUES (165,'Jackson Browne');
INSERT INTO "artists" VALUES (166,'Avril Lavigne');
INSERT INTO "artists" VALUES (167,'Big & Rich');
INSERT INTO "artists" VALUES (168,'Youssou N''Dour');
INSERT INTO "artists" VALUES (169,'Black Eyed Peas');
INSERT INTO "artists" VALUES (170,'Jack Johnson');
INSERT INTO "artists" VALUES (171,'Ben Harper');
INSERT INTO "artists" VALUES (172,'Snow Patrol');
INSERT INTO "artists" VALUES (173,'Matisyahu');
INSERT INTO "artists" VALUES (174,'The Postal Service');
INSERT INTO "artists" VALUES (175,'Jaguares');
INSERT INTO "artists" VALUES (176,'The Flaming Lips');
INSERT INTO "artists" VALUES (177,'Jack''s Mannequin & Mick Fleetwood');
INSERT INTO "artists" VALUES (178,'Regina Spektor');
INSERT INTO "artists" VALUES (179,'Scorpions');
INSERT INTO "artists" VALUES (180,'House Of Pain');
INSERT INTO "artists" VALUES (181,'Xis');
INSERT INTO "artists" VALUES (182,'Nega Gizza');
INSERT INTO "artists" VALUES (183,'Gustavo & Andres Veiga & Salazar');
INSERT INTO "artists" VALUES (184,'Rodox');
INSERT INTO "artists" VALUES (185,'Charlie Brown Jr.');
INSERT INTO "artists" VALUES (186,'Pedro Luís E A Parede');
INSERT INTO "artists" VALUES (187,'Los Hermanos');
INSERT INTO "artists" VALUES (188,'Mundo Livre S/A');
INSERT INTO "artists" VALUES (189,'Otto');
INSERT INTO "artists" VALUES (190,'Instituto');
INSERT INTO "artists" VALUES (191,'Nação Zumbi');
INSERT INTO "artists" VALUES (192,'DJ Dolores & Orchestra Santa Massa');
INSERT INTO "artists" VALUES (193,'Seu Jorge');
INSERT INTO "artists" VALUES (194,'Sabotage E Instituto');
INSERT INTO "artists" VALUES (195,'Stereo Maracana');
INSERT INTO "artists" VALUES (196,'Cake');
INSERT INTO "artists" VALUES (197,'Aisha Duo');
INSERT INTO "artists" VALUES (198,'Habib Koité and Bamada');
INSERT INTO "artists" VALUES (199,'Karsh Kale');
INSERT INTO "artists" VALUES (200,'The Posies');
INSERT INTO "artists" VALUES (201,'Luciana Souza/Romero Lubambo');
INSERT INTO "artists" VALUES (202,'Aaron Goldberg');
INSERT INTO "artists" VALUES (203,'Nicolaus Esterhazy Sinfonia');
INSERT INTO "artists" VALUES (204,'Temple of the Dog');
INSERT INTO "artists" VALUES (205,'Chris Cornell');
INSERT INTO "artists" VALUES (206,'Alberto Turco & Nova Schola Gregoriana');
INSERT INTO "artists" VALUES (207,'Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO "artists" VALUES (208,'English Concert & Trevor Pinnock');
INSERT INTO "artists" VALUES (209,'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "artists" VALUES (210,'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO "artists" VALUES (211,'Wilhelm Kempff');
INSERT INTO "artists" VALUES (212,'Yo-Yo Ma');
INSERT INTO "artists" VALUES (213,'Scholars Baroque Ensemble');
INSERT INTO "artists" VALUES (214,'Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO "artists" VALUES (215,'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO "artists" VALUES (216,'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO "artists" VALUES (217,'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO "artists" VALUES (218,'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO "artists" VALUES (219,'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO "artists" VALUES (220,'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO "artists" VALUES (221,'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO "artists" VALUES (222,'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO "artists" VALUES (223,'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO "artists" VALUES (224,'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO "artists" VALUES (225,'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO "artists" VALUES (226,'Eugene Ormandy');
INSERT INTO "artists" VALUES (227,'Luciano Pavarotti');
INSERT INTO "artists" VALUES (228,'Leonard Bernstein & New York Philharmonic');
INSERT INTO "artists" VALUES (229,'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO "artists" VALUES (230,'Aaron Copland & London Symphony Orchestra');
INSERT INTO "artists" VALUES (231,'Ton Koopman');
INSERT INTO "artists" VALUES (232,'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO "artists" VALUES (233,'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO "artists" VALUES (234,'Orchestra of The Age of Enlightenment');
INSERT INTO "artists" VALUES (235,'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO "artists" VALUES (236,'James Levine');
INSERT INTO "artists" VALUES (237,'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO "artists" VALUES (238,'Maurizio Pollini');
INSERT INTO "artists" VALUES (239,'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO "artists" VALUES (240,'Gustav Mahler');
INSERT INTO "artists" VALUES (241,'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO "artists" VALUES (242,'Edo de Waart & San Francisco Symphony');
INSERT INTO "artists" VALUES (243,'Antal Doráti & London Symphony Orchestra');
INSERT INTO "artists" VALUES (244,'Choir Of Westminster Abbey & Simon Preston');
INSERT INTO "artists" VALUES (245,'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO "artists" VALUES (246,'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "artists" VALUES (247,'The King''s Singers');
INSERT INTO "artists" VALUES (248,'Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO "artists" VALUES (249,'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO "artists" VALUES (250,'Christopher O''Riley');
INSERT INTO "artists" VALUES (251,'Fretwork');
INSERT INTO "artists" VALUES (252,'Amy Winehouse');
INSERT INTO "artists" VALUES (253,'Calexico');
INSERT INTO "artists" VALUES (254,'Otto Klemperer & Philharmonia Orchestra');
INSERT INTO "artists" VALUES (255,'Yehudi Menuhin');
INSERT INTO "artists" VALUES (256,'Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO "artists" VALUES (257,'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO "artists" VALUES (258,'Les Arts Florissants & William Christie');
INSERT INTO "artists" VALUES (259,'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO "artists" VALUES (260,'Adrian Leaper & Doreen de Feis');
INSERT INTO "artists" VALUES (261,'Roger Norrington, London Classical Players');
INSERT INTO "artists" VALUES (262,'Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO "artists" VALUES (263,'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO "artists" VALUES (264,'Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO "artists" VALUES (265,'Julian Bream');
INSERT INTO "artists" VALUES (266,'Martin Roscoe');
INSERT INTO "artists" VALUES (267,'Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO "artists" VALUES (268,'Itzhak Perlman');
INSERT INTO "artists" VALUES (269,'Michele Campanella');
INSERT INTO "artists" VALUES (270,'Gerald Moore');
INSERT INTO "artists" VALUES (271,'Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO "artists" VALUES (272,'Emerson String Quartet');
INSERT INTO "artists" VALUES (273,'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO "artists" VALUES (274,'Nash Ensemble');
INSERT INTO "artists" VALUES (275,'Philip Glass Ensemble');
CREATE INDEX IF NOT EXISTS "IFK_AlbumArtistId" ON "albums" (
	"ArtistId"
);
COMMIT;
